In [1]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [2]:
X = np.arange(6).reshape(3, 2)

In [3]:
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [9]:
poly = PolynomialFeatures(2)

In [10]:
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [11]:
poly = PolynomialFeatures(1)

In [12]:
poly.fit_transform(X)

array([[1., 0., 1.],
       [1., 2., 3.],
       [1., 4., 5.]])

In [13]:
poly = PolynomialFeatures(0)

In [14]:
poly.fit_transform(X)

array([[1.],
       [1.],
       [1.]])